version: "3"
services:
  monapp:
    image: monimage
    depends_on:
      - redis
    ports:
      - "80:80"
    networks:
      - monreseau
    
  redis:
    image: redis
    networks:
      - monreseau

networks:
  monreseau:
